=======================================================================================
Task 1 
There are three different tables as given above. Please make three dataframe in python 
and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# dictionary for Employee data
employee_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"],
    "Gender": ["M", "F", "M", "F", "F"],
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"],
    "Age": [25, 27, 29, 31, 30]
}

In [3]:
# dictionary into DataFrame
employee_df = pd.DataFrame(employee_data)

In [4]:
# display DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
# save employee DataFrame to CSV file
employee_df.to_csv("employee.csv", index=False)

In [6]:
# dictionary for Seniority data
seniority_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005"],
    "Designation Level": [2, 2, 3, 2, 3]
}

In [7]:
# dictionary into DataFrame
seniority_df = pd.DataFrame(seniority_data)

In [8]:
# display DataFrame
seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [9]:
# save seniority DataFrame to CSV file
seniority_df.to_csv("seniority.csv", index=False)

In [10]:
# dictionary for Project data
project_data = {
    "ID": ["A001", "A002", "A003", "A004", "A005", "A002", "A005", "A003", "A001", "A003", "A001", "A004", "A004", "A005"],
    "Project": ["Project 1", "Project 2", "Project 3", "Project 4", "Project 5",
                "Project 6", "Project 7", "Project 8", "Project 9", "Project 10",
                "Project 11", "Project 12", "Project 13", "Project 14"],
    "Cost": [1002000, 2000000, 4500000, 5500000, np.nan,
             680000, 400000, 350000, np.nan, 300000,
             2000000, 1000000, 3000000, 200000],
    "Status": ["Finished", "Ongoing", "Finished", "Ongoing", "Finished",
               "Failed", "Finished", "Failed", "Ongoing", "Finished",
               "Failed", "Ongoing", "Finished", "Finished"]
}

In [11]:
# dictionary into DataFrame
project_df = pd.DataFrame(project_data)

In [12]:
# Display DataFrame
project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [13]:
# Save project DataFrame to CSV file
project_df.to_csv("project.csv", index=False)

In [14]:
# Load employee CSV file
employee_df = pd.read_csv("employee.csv")

# Load seniority CSV file
seniority_df = pd.read_csv("seniority.csv")

# Load project CSV file
project_df = pd.read_csv("project.csv")

=======================================================================================Task 2 

The cost column in the dataframe “Project” has some missing values. Your task is to 
compute these missing values. Replace the missing values by running average. You 
should use the “For” loop for this task.

In [15]:
# Check how many missing values are in Cost column
project_df["Cost"].isnull().sum()

np.int64(2)

In [16]:
# Create variables to store running total and count
running_sum = 0
count = 0

# Loop through each row index in project_df
for i in range(len(project_df)):

    # Check if value is NOT missing
    if not pd.isnull(project_df.loc[i, "Cost"]):
        
        # Add value to running sum
        running_sum += project_df.loc[i, "Cost"]
        
        # Increase count
        count += 1
    
    # If value IS missing
    else:
        
        # Calculate running average
        running_avg = running_sum / count
        
        # Replace missing value with running average
        project_df.loc[i, "Cost"] = running_avg

In [17]:
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [18]:
project_df["Cost"].isnull().sum()

np.int64(0)

In [19]:
# Save updated project data back to CSV
project_df.to_csv("project.csv", index=False)

=======================================================================================Task 3

Split the name column in the Employee dataframe into two new columns “First Name”,
and “LastName” and remove the older “name” column.

In [20]:
# Reload employee data from CSV
employee_df = pd.read_csv("employee.csv")

In [21]:
# Display DataFrame
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [22]:
# Split Name column into First Name and Last Name
employee_df[["First Name", "Last Name"]] = employee_df["Name"].str.split(" ", expand=True)

In [23]:
# Drop the old Name column
employee_df = employee_df.drop("Name", axis=1)

In [24]:
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [25]:
# Save updated employee data back to CSV
employee_df.to_csv("employee.csv", index=False)

=======================================================================================Task 4

Join all three dataframes in one single dataframe. Name it “Final”

In [26]:
# Load employee data
employee_df = pd.read_csv("employee.csv")

# Load seniority data
seniority_df = pd.read_csv("seniority.csv")

# Load project data
project_df = pd.read_csv("project.csv")

In [27]:
# Merge employee and seniority data on ID
emp_seniority = pd.merge(employee_df, seniority_df, on="ID")

# Display result
emp_seniority

     ID Gender     City  Age First Name  Last Name  Designation Level
0  A001      M    Paris   25       John      Alter                  2
1  A002      F   London   27      Alice  Luxumberg                  2
2  A003      M   Berlin   29        Tom  Sabestine                  3
3  A004      F  Newyork   31       Nina      Adgra                  2
4  A005      F   Madrid   30        Amy      Johny                  3

In [28]:
# Merge previous result with project data on ID
Final = pd.merge(emp_seniority, project_df, on="ID")

# Display Final DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [29]:
# Save Final dataframe
Final.to_csv("Final.csv", index=False)

=======================================================================================Task 5

Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
cost only to employees who have finished the projects.

In [30]:
# Create Bonus column

Final["Bonus"] = 0  # Initialize column with 0

# Loop through each row
for i in range(len(Final)):
    
    # If project status is Finished
    if Final.loc[i, "Status"] == "Finished":
        
        # Give 5% bonus
        Final.loc[i, "Bonus"] = Final.loc[i, "Cost"] * 0.05

In [31]:
Final[["Project", "Cost", "Status", "Bonus"]]

       Project          Cost    Status   Bonus
0    Project 1  1.002000e+06  Finished   50100
1    Project 9  2.061714e+06   Ongoing       0
2   Project 11  2.000000e+06    Failed       0
3    Project 2  2.000000e+06   Ongoing       0
4    Project 6  6.800000e+05    Failed       0
5    Project 3  4.500000e+06  Finished  225000
6    Project 8  3.500000e+05    Failed       0
7   Project 10  3.000000e+05  Finished   15000
8    Project 4  5.500000e+06   Ongoing       0
9   Project 12  1.000000e+06   Ongoing       0
10  Project 13  3.000000e+06  Finished  150000
11   Project 5  3.250500e+06  Finished  162525
12   Project 7  4.000000e+05  Finished   20000
13  Project 14  2.000000e+05  Finished   10000

In [32]:
Final.to_csv("Final.csv", index=False)

=======================================================================================Task 6

Demote the designation level by 1, whose projects have status “fail”. Delete the
employees record whose designation level is above 4.

In [33]:
# Loop through each row
for i in range(len(Final)):
    
    # If project status is Failed
    if Final.loc[i, "Status"] == "Failed":
        
        # Reduce designation level by 1
        Final.loc[i, "Designation Level"] += 1

In [34]:
# Remove rows where designation level is greater than 4
Final = Final[Final["Designation Level"] <= 4]

In [35]:
Final[["ID", "Project", "Status", "Designation Level"]]

      ID     Project    Status  Designation Level
0   A001   Project 1  Finished                  2
1   A001   Project 9   Ongoing                  2
2   A001  Project 11    Failed                  3
3   A002   Project 2   Ongoing                  2
4   A002   Project 6    Failed                  3
5   A003   Project 3  Finished                  3
6   A003   Project 8    Failed                  4
7   A003  Project 10  Finished                  3
8   A004   Project 4   Ongoing                  2
9   A004  Project 12   Ongoing                  2
10  A004  Project 13  Finished                  2
11  A005   Project 5  Finished                  3
12  A005   Project 7  Finished                  3
13  A005  Project 14  Finished                  3

In [36]:
Final.to_csv("Final.csv", index=False)

=======================================================================================Task 7

Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [37]:
# Loop through each row
for i in range(len(Final)):
    
    # If Gender is Male
    if Final.loc[i, "Gender"] == "M":
        Final.loc[i, "First Name"] = "Mr. " + Final.loc[i, "First Name"]
    
    # If Gender is Female
    elif Final.loc[i, "Gender"] == "F":
        Final.loc[i, "First Name"] = "Mrs. " + Final.loc[i, "First Name"]

In [38]:
# Remove Gender column
Final = Final.drop("Gender", axis=1)

In [39]:
Final.head()

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0

In [40]:
Final.to_csv("Final.csv", index=False)

=======================================================================================Task 8

Promote designation level by 1 for the employees whose age is more than 29 years using
IF condition.

In [41]:
# Loop through each row
for i in range(len(Final)):
    
    # If Age is greater than 29
    if Final.loc[i, "Age"] > 29:
        
        # Increase designation level by 1
        Final.loc[i, "Designation Level"] -= 1

In [42]:
Final[["ID", "Age", "Designation Level"]]

      ID  Age  Designation Level
0   A001   25                  2
1   A001   25                  2
2   A001   25                  3
3   A002   27                  2
4   A002   27                  3
5   A003   29                  3
6   A003   29                  4
7   A003   29                  3
8   A004   31                  1
9   A004   31                  1
10  A004   31                  1
11  A005   30                  2
12  A005   30                  2
13  A005   30                  2

In [43]:
Final.to_csv("Final.csv", index=False)

=======================================================================================Task 9

Add the cost of all projects for each Employee and save it in new dataframe
“TotalProjCost” with three columns ID, First Name, and Total cost

In [44]:
# Group by ID and First Name
TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename Cost column to Total Cost
TotalProjCost = TotalProjCost.rename(columns={"Cost": "Total Cost"})

# Display the new DataFrame
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [45]:
# Save TotalProjCost dataframe
TotalProjCost.to_csv("TotalProjCost.csv", index=False)

=======================================================================================Task 10

Print all the employee details whose city name contains the letter “o” in it.

In [46]:
# Filter employees whose City contains letter 'o'
filtered_employees = Final[Final["City"].str.contains("o", case=False)]

# Display result
filtered_employees

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000